### PR TITLE
Fix micro benchmarks

### LINKED ISSUE #440: [BUG] Benchmark `lsm-tree-micro-bench` fails with error
**Describe the bug**
```
lsm-tree-micro-bench: FsError {fsErrorType = FsResourceAlreadyExist, fsErrorPath = /private/var/folders/9b/tq2xht4j42jdnhy6x5nt8r040000gn/T/lookupsInBatchesEnv-188f880fc0b9ac57, fsErrorString = "File exists", fsErrorNo = Just (Errno 17), fsErrorStack = CallStack (from HasCallStack):
  prettyCallStack, called at src/System/FS/API/Types.hs:393:23 in fs-p-0.3.0.1-39dcdd21:System.FS.API.Types
  ioToFsError, called at src/System/FS/IO.hs:113:41 in fs-p-0.3.0.1-39dcdd21:System.FS.IO
  handleError, called at src/System/FS/IO.hs:109:23 in fs-p-0.3.0.1-39dcdd21:System.FS.IO
  rethrowFsError, called at src/System/FS/IO.hs:50:21 in fs-p-0.3.0.1-39dcdd21:System.FS.IO
  hOpen, called at src/System/FS/API.hs:63:5 in fs-p-0.3.0.1-39dcdd21:System.FS.API
  a use of `FS.hOpen', called at src/Database/LSMTree/Internal/WriteBufferBlobs.hs:125:23 in lsm-tree-0.1.0.0-inplace:Database.LSMTree.Internal.WriteBufferBlobs, fsLimitation = False}
Benchmark lsm-tree-micro-bench: ERROR
Error: cabal: Benchmarks failed for bench:lsm-tree-micro-bench from
lsm-tree-0.1.0.0.
```

**To Reproduce**
1. Check out #426 
2. Run `cabal bench lsm-tree-micro-bench`

**Output**
If applicable, add log excerpts, screenshots or other files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 13.7
 - GHC: GHC 9.8.2

**Additional context**
The bug is not specific to #426 and already exists on 23939c1e3c77c132af2b4b0941c38030a792b28e.

### PR DESCRIPTION
**Pull request by mheinzel**
Some micro benchmarks don't run any more. I fixed two where the benchmark environment code got broken by recent changes.

Fixes #440. (this was one of them)

### CODE REVIEW

**Comment by jorisdral** [comment]
Related: https://github.com/IntersectMBO/lsm-tree/issues/440

**Review by dcoutts — APPROVED** [review]
LGTM

File: bench/micro/Bench/Database/LSMTree/Internal/Merge.hs [hunk 1]
```diff
@@ -201,28 +201,28 @@ benchMerge conf@Config{name} =
             --    thread `runs` through the environment, too.
             -- 2. It forces the result to normal form, which would traverse the
             --    whole run, so we force to WHNF ourselves and just return `()`.
+
+            -- We make sure to immediately close resulting runs so we don't run
+            -- out of file handles or disk space. However, we don't want it to
+            -- be part of the measurement, as it includes deleting files.
+            -- Therefore, ... TODO
```
Comment (jorisdral) [inline bench/micro/Bench/Database/LSMTree/Internal/Merge.hs:208]: There is a dangling TODO here

File: bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs [hunk 2]
```diff
@@ -242,25 +241,26 @@ lookupsEnv g nentries npos nneg = do
...
     pure (entries', lookups')
 
 -- TODO: tweak distribution
-randomEntry :: StdGen -> (Entry UTxOValue BlobSpan, StdGen)
+randomEntry :: StdGen -> (Entry UTxOValue ByteString, StdGen)
 randomEntry g = frequency [
       (20, \g' -> let (!v, !g'') = uniform g' in (Insert v, g''))
     , (1,  \g' -> let (!v, !g'') = uniform g'
-                      (!b, !g''') = genBlobSpan g''
+                      (!b, !g''') = randomByteStringR (0, 2000) g''  -- < 2kB
```
Comment (jorisdral) [inline bench/micro/Bench/Database/LSMTree/Internal/Lookup.hs:255]: You can generate much smaller blobs. It would speed up the benchmark setup, and the performance of the lookups code does not depend on the blob size. But it's maybe also not super important because inserts with blobs are generated only rarely

**Review by jorisdral — COMMENTED** [review]
Very nice!

File: bench/micro/Bench/Database/LSMTree/Internal/Merge.hs (hunk 1 above)
Comment (mheinzel) [reply bench/micro/Bench/Database/LSMTree/Internal/Merge.hs:208]: Oops, that slipped through. Thanks for pointing it out. https://github.com/IntersectMBO/lsm-tree/pull/547
