### PR TITLE
Fix level calculations for tiny runs in the ScheduledMerges prototype

### LINKED ISSUE #236: Assertion failure in `ScheduledMerges` prototype
https://github.com/IntersectMBO/lsm-tree/actions/runs/9351899757/job/25738763256?pr=235

### PR DESCRIPTION
**Pull request by mheinzel**
Fixes #236 

I'm just pushing the regression test first so you can see the test failure in CI.

### CODE REVIEW

File: prototypes/ScheduledMerges.hs [hunk 1]
```diff
@@ -416,6 +420,14 @@ update tr (LSMHandle scr lsmr) k op = do
       else
         writeSTRef lsmr (LSMContent wb' ls)
 
+supply :: LSM s -> Credit -> ST s ()
+supply (LSMHandle scr lsmr) credits = do
+    LSMContent _ ls <- readSTRef lsmr
+    modifySTRef' scr (+1)
+    supplyCredits credits ls
+    ok <- invariant ls
+    assert ok $ return ()
```
Comment (mheinzel) [inline prototypes/ScheduledMerges.hs:429]: I exposed this to make the test case simpler, just supplying merge credits instead of having to do inserts that are not relevant to the problem.

**Review by mheinzel — COMMENTED** [review]
The regression test and ability to show the tracer log with a failure are not strictly necessary, but I created them to track down the bug and thought it doesn't hurt to commit them.

**Review by jorisdral — APPROVED** [review]
LGTM! Nice catch
